sudo: false

language: node_js
node_js:
  - 12.4.0

cache: yarn
os: linux

branches:
  only:
    - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH="$HOME/.yarn/bin:$PATH"

install:
  - yarn

script:
  - yarn clean
  - yarn build
  - yarn lint-stage
  - yarn jest
