language: node_js
os: linux
node_js:
  - 12.4.0
cache: yarn

env:
  global:
    - CODECOV_TOKEN=$CODECOV_TOKEN

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.16.0
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - yarn
script:
  - yarn clean
  - yarn build
  - yarn lint-stage
  - yarn jest
after_success:
  - bash <(curl -s https://codecov.io/bash) -v
